/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttributionContext : Attribution context information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributionContext {
    /// Observed MITRE ATT&CK TTPs
    #[serde(rename = "observedTTPs", skip_serializing_if = "Option::is_none")]
    pub observed_ttps: Option<Vec<String>>,
    /// Targeted sector/industry
    #[serde(rename = "targetedSector", skip_serializing_if = "Option::is_none")]
    pub targeted_sector: Option<String>,
    /// Geographic region of targets
    #[serde(rename = "targetRegion", skip_serializing_if = "Option::is_none")]
    pub target_region: Option<String>,
    /// Campaign timeframe
    #[serde(rename = "timeframe", skip_serializing_if = "Option::is_none")]
    pub timeframe: Option<String>,
    /// Known malware families observed
    #[serde(rename = "malwareFamilies", skip_serializing_if = "Option::is_none")]
    pub malware_families: Option<Vec<String>>,
}

impl AttributionContext {
    /// Attribution context information
    pub fn new() -> AttributionContext {
        AttributionContext {
            observed_ttps: None,
            targeted_sector: None,
            target_region: None,
            timeframe: None,
            malware_families: None,
        }
    }
}

