/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttributeRequest : Request for threat actor attribution and campaign clustering
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeRequest {
    /// List of indicators for attribution analysis (max 500)
    #[serde(rename = "indicators")]
    pub indicators: Vec<String>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::AttributionContext>>,
}

impl AttributeRequest {
    /// Request for threat actor attribution and campaign clustering
    pub fn new(indicators: Vec<String>) -> AttributeRequest {
        AttributeRequest {
            indicators,
            context: None,
        }
    }
}

