/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BitsquattingConfig : Configuration for bitsquatting (bit-flip) variations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BitsquattingConfig {
    /// Maximum bit flips per character
    #[serde(rename = "max_bit_flips", skip_serializing_if = "Option::is_none")]
    pub max_bit_flips: Option<i32>,
}

impl BitsquattingConfig {
    /// Configuration for bitsquatting (bit-flip) variations
    pub fn new() -> BitsquattingConfig {
        BitsquattingConfig {
            max_bit_flips: None,
        }
    }
}

