/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlacklistScores : Blacklist scores at different network levels
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlacklistScores {
    /// IP-level blacklist score
    #[serde(rename = "ip_score", skip_serializing_if = "Option::is_none")]
    pub ip_score: Option<f64>,
    /// Network prefix blacklist score
    #[serde(rename = "prefix_score", skip_serializing_if = "Option::is_none")]
    pub prefix_score: Option<f64>,
    /// ASN-level blacklist score
    #[serde(rename = "asn_score", skip_serializing_if = "Option::is_none")]
    pub asn_score: Option<f64>,
}

impl BlacklistScores {
    /// Blacklist scores at different network levels
    pub fn new() -> BlacklistScores {
        BlacklistScores {
            ip_score: None,
            prefix_score: None,
            asn_score: None,
        }
    }
}

