/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkRequest : Request payload for bulk enrichment of multiple IP addresses and domains
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkRequest {
    /// List of indicators (IP addresses or domains) to enrich. Mix of IPs and domains is supported.
    #[serde(rename = "indicators")]
    pub indicators: Vec<String>,
    /// Additional data modules to include for each indicator. Same options as single indicator endpoint.
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<std::collections::HashSet<Include>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::BulkOptions>>,
}

impl BulkRequest {
    /// Request payload for bulk enrichment of multiple IP addresses and domains
    pub fn new(indicators: Vec<String>) -> BulkRequest {
        BulkRequest {
            indicators,
            include: None,
            options: None,
        }
    }
}
/// Additional data modules to include for each indicator. Same options as single indicator endpoint.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Include {
    #[serde(rename = "routing")]
    Routing,
    #[serde(rename = "rpki")]
    Rpki,
    #[serde(rename = "whois")]
    Whois,
    #[serde(rename = "dns_details")]
    DnsDetails,
    #[serde(rename = "ip_intelligence")]
    IpIntelligence,
}

impl Default for Include {
    fn default() -> Include {
        Self::Routing
    }
}

