/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeEvent : A single detected change event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeEvent {
    /// When the change was detected
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// Field that changed (dot notation, e.g., 'dns.a_record')
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(rename = "oldValue", skip_serializing_if = "Option::is_none")]
    pub old_value: Option<serde_json::Value>,
    #[serde(rename = "newValue", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<serde_json::Value>,
    /// Category of the change (dns, whois, ssl, etc.)
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Severity of the change: low, medium, high
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
}

impl ChangeEvent {
    /// A single detected change event
    pub fn new() -> ChangeEvent {
        ChangeEvent {
            timestamp: None,
            field: None,
            old_value: None,
            new_value: None,
            category: None,
            severity: None,
        }
    }
}

