/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeTrackingRequest : Request to start or update change tracking for an indicator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeTrackingRequest {
    /// Fields to track for changes. Valid values depend on indicator type.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    /// How often to check for changes
    #[serde(rename = "frequency", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<Frequency>,
    /// Whether tracking is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl ChangeTrackingRequest {
    /// Request to start or update change tracking for an indicator
    pub fn new() -> ChangeTrackingRequest {
        ChangeTrackingRequest {
            fields: None,
            frequency: None,
            enabled: None,
        }
    }
}
/// How often to check for changes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Frequency {
    #[serde(rename = "hourly")]
    Hourly,
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "weekly")]
    Weekly,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::Hourly
    }
}

