/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeTrackingResponse : Change tracking response with configuration and detected changes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeTrackingResponse {
    /// The indicator value (IP or domain)
    #[serde(rename = "indicator", skip_serializing_if = "Option::is_none")]
    pub indicator: Option<String>,
    /// Indicator type: ip or domain
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "tracking", skip_serializing_if = "Option::is_none")]
    pub tracking: Option<Box<models::TrackingConfig>>,
    /// List of detected changes
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<models::ChangeEvent>>,
    #[serde(rename = "baseline", skip_serializing_if = "Option::is_none")]
    pub baseline: Option<serde_json::Value>,
    /// When the baseline was captured
    #[serde(rename = "baselineCapturedAt", skip_serializing_if = "Option::is_none")]
    pub baseline_captured_at: Option<String>,
    /// Total number of changes detected
    #[serde(rename = "totalChanges", skip_serializing_if = "Option::is_none")]
    pub total_changes: Option<i32>,
    /// Error message if operation failed
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Whether the operation was successful
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ChangeTrackingResponse {
    /// Change tracking response with configuration and detected changes
    pub fn new() -> ChangeTrackingResponse {
        ChangeTrackingResponse {
            indicator: None,
            r#type: None,
            tracking: None,
            changes: None,
            baseline: None,
            baseline_captured_at: None,
            total_changes: None,
            error: None,
            success: None,
        }
    }
}

