/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CorrelateOptions : Correlation analysis options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CorrelateOptions {
    /// Time window for temporal correlation
    #[serde(rename = "timeWindow", skip_serializing_if = "Option::is_none")]
    pub time_window: Option<String>,
    /// Types of correlation to analyze
    #[serde(rename = "correlationTypes", skip_serializing_if = "Option::is_none")]
    pub correlation_types: Option<Vec<String>>,
    /// Minimum confidence threshold
    #[serde(rename = "minConfidence", skip_serializing_if = "Option::is_none")]
    pub min_confidence: Option<f64>,
    /// Include industry breakdown
    #[serde(rename = "includeIndustryBreakdown", skip_serializing_if = "Option::is_none")]
    pub include_industry_breakdown: Option<bool>,
}

impl CorrelateOptions {
    /// Correlation analysis options
    pub fn new() -> CorrelateOptions {
        CorrelateOptions {
            time_window: None,
            correlation_types: None,
            min_confidence: None,
            include_industry_breakdown: None,
        }
    }
}

