/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CorrelateRequest : Request for cross-customer indicator correlation analysis
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CorrelateRequest {
    /// List of indicators to correlate (max 100)
    #[serde(rename = "indicators")]
    pub indicators: Vec<String>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::CorrelateOptions>>,
}

impl CorrelateRequest {
    /// Request for cross-customer indicator correlation analysis
    pub fn new(indicators: Vec<String>) -> CorrelateRequest {
        CorrelateRequest {
            indicators,
            options: None,
        }
    }
}

