/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsInfo : DNS records and resolution data for the domain
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsInfo {
    #[serde(rename = "arecords", skip_serializing_if = "Option::is_none")]
    pub arecords: Option<Vec<String>>,
    /// A records (IPv4 addresses)
    #[serde(rename = "a_records", skip_serializing_if = "Option::is_none")]
    pub a_records: Option<Vec<String>>,
    /// AAAA records (IPv6 addresses)
    #[serde(rename = "aaaa_records", skip_serializing_if = "Option::is_none")]
    pub aaaa_records: Option<Vec<String>>,
    /// MX records (mail servers) with priority and hostname
    #[serde(rename = "mx_records", skip_serializing_if = "Option::is_none")]
    pub mx_records: Option<Vec<serde_json::Value>>,
    /// NS records (name servers)
    #[serde(rename = "ns_records", skip_serializing_if = "Option::is_none")]
    pub ns_records: Option<Vec<String>>,
    /// TXT records (text records for SPF, DKIM, etc.)
    #[serde(rename = "txt_records", skip_serializing_if = "Option::is_none")]
    pub txt_records: Option<Vec<String>>,
    /// CNAME records (canonical name aliases)
    #[serde(rename = "cname_records", skip_serializing_if = "Option::is_none")]
    pub cname_records: Option<Vec<String>>,
}

impl DnsInfo {
    /// DNS records and resolution data for the domain
    pub fn new() -> DnsInfo {
        DnsInfo {
            arecords: None,
            a_records: None,
            aaaa_records: None,
            mx_records: None,
            ns_records: None,
            txt_records: None,
            cname_records: None,
        }
    }
}

