/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DomainReputationDetails : Detailed infrastructure and individual IP scores
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainReputationDetails {
    /// Domain's A record IP addresses
    #[serde(rename = "domain_ips", skip_serializing_if = "Option::is_none")]
    pub domain_ips: Option<Vec<String>>,
    /// Individual scores for each domain IP
    #[serde(rename = "domain_ip_scores", skip_serializing_if = "Option::is_none")]
    pub domain_ip_scores: Option<std::collections::HashMap<String, f64>>,
    /// Nameserver domain names
    #[serde(rename = "nameserver_domains", skip_serializing_if = "Option::is_none")]
    pub nameserver_domains: Option<Vec<String>>,
    /// IP addresses of nameservers
    #[serde(rename = "nameserver_ips", skip_serializing_if = "Option::is_none")]
    pub nameserver_ips: Option<Vec<String>>,
    /// Individual scores for each nameserver IP
    #[serde(rename = "nameserver_ip_scores", skip_serializing_if = "Option::is_none")]
    pub nameserver_ip_scores: Option<std::collections::HashMap<String, f64>>,
    /// Mail server domain names
    #[serde(rename = "mailserver_domains", skip_serializing_if = "Option::is_none")]
    pub mailserver_domains: Option<Vec<String>>,
    /// IP addresses of mail servers
    #[serde(rename = "mailserver_ips", skip_serializing_if = "Option::is_none")]
    pub mailserver_ips: Option<Vec<String>>,
    /// Individual scores for each mail server IP
    #[serde(rename = "mailserver_ip_scores", skip_serializing_if = "Option::is_none")]
    pub mailserver_ip_scores: Option<std::collections::HashMap<String, f64>>,
}

impl DomainReputationDetails {
    /// Detailed infrastructure and individual IP scores
    pub fn new() -> DomainReputationDetails {
        DomainReputationDetails {
            domain_ips: None,
            domain_ip_scores: None,
            nameserver_domains: None,
            nameserver_ips: None,
            nameserver_ip_scores: None,
            mailserver_domains: None,
            mailserver_ips: None,
            mailserver_ip_scores: None,
        }
    }
}

