/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EarlyWarning : Early warning signal
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EarlyWarning {
    /// Warning type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Severity level
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    /// Warning message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Detection timestamp
    #[serde(rename = "detectedAt", skip_serializing_if = "Option::is_none")]
    pub detected_at: Option<String>,
}

impl EarlyWarning {
    /// Early warning signal
    pub fn new() -> EarlyWarning {
        EarlyWarning {
            r#type: None,
            severity: None,
            message: None,
            detected_at: None,
        }
    }
}

