/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryData {
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<Vec<serde_json::Value>>,
    #[serde(rename = "total_records", skip_serializing_if = "Option::is_none")]
    pub total_records: Option<i32>,
    #[serde(rename = "oldest_date", skip_serializing_if = "Option::is_none")]
    pub oldest_date: Option<String>,
    #[serde(rename = "newest_date", skip_serializing_if = "Option::is_none")]
    pub newest_date: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl HistoryData {
    pub fn new() -> HistoryData {
        HistoryData {
            records: None,
            total_records: None,
            oldest_date: None,
            newest_date: None,
            message: None,
        }
    }
}

