/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryResponse {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::QueryInfo>>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Box<models::HistoryData>>,
}

impl HistoryResponse {
    pub fn new() -> HistoryResponse {
        HistoryResponse {
            query: None,
            history: None,
        }
    }
}

