/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HomoglyphConfig : Configuration for homoglyph (look-alike character) variations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HomoglyphConfig {
    /// Include Cyrillic character substitutions
    #[serde(rename = "cyrillic", skip_serializing_if = "Option::is_none")]
    pub cyrillic: Option<bool>,
    /// Include Greek character substitutions
    #[serde(rename = "greek", skip_serializing_if = "Option::is_none")]
    pub greek: Option<bool>,
    /// Include Latin character substitutions
    #[serde(rename = "latin", skip_serializing_if = "Option::is_none")]
    pub latin: Option<bool>,
    /// Maximum number of character substitutions per domain
    #[serde(rename = "max_substitutions", skip_serializing_if = "Option::is_none")]
    pub max_substitutions: Option<i32>,
}

impl HomoglyphConfig {
    /// Configuration for homoglyph (look-alike character) variations
    pub fn new() -> HomoglyphConfig {
        HomoglyphConfig {
            cyrillic: None,
            greek: None,
            latin: None,
            max_substitutions: None,
        }
    }
}

