/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndicatorResponse : Comprehensive intelligence response for an IP address or domain indicator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndicatorResponse {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::QueryInfo>>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::SummaryInfo>>,
    #[serde(rename = "geolocation", skip_serializing_if = "Option::is_none")]
    pub geolocation: Option<serde_json::Value>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<serde_json::Value>,
    #[serde(rename = "routing", skip_serializing_if = "Option::is_none")]
    pub routing: Option<serde_json::Value>,
    #[serde(rename = "isp", skip_serializing_if = "Option::is_none")]
    pub isp: Option<serde_json::Value>,
    #[serde(rename = "registration", skip_serializing_if = "Option::is_none")]
    pub registration: Option<serde_json::Value>,
    #[serde(rename = "dns", skip_serializing_if = "Option::is_none")]
    pub dns: Option<Box<models::DnsInfo>>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<models::RelationshipInfo>>,
    #[serde(rename = "reputation", skip_serializing_if = "Option::is_none")]
    pub reputation: Option<Box<models::ReputationInfo>>,
    #[serde(rename = "security", skip_serializing_if = "Option::is_none")]
    pub security: Option<serde_json::Value>,
    #[serde(rename = "rpki", skip_serializing_if = "Option::is_none")]
    pub rpki: Option<serde_json::Value>,
    /// When domain is queried with include=ip_intelligence, contains full intelligence for each resolved IP
    #[serde(rename = "ip_intelligence", skip_serializing_if = "Option::is_none")]
    pub ip_intelligence: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::MetadataInfo>>,
}

impl IndicatorResponse {
    /// Comprehensive intelligence response for an IP address or domain indicator
    pub fn new() -> IndicatorResponse {
        IndicatorResponse {
            query: None,
            summary: None,
            geolocation: None,
            network: None,
            routing: None,
            isp: None,
            registration: None,
            dns: None,
            relationships: None,
            reputation: None,
            security: None,
            rpki: None,
            ip_intelligence: None,
            metadata: None,
        }
    }
}

