/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvestigateRequest : Request for comprehensive AI threat investigation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvestigateRequest {
    /// The indicator to investigate
    #[serde(rename = "indicator")]
    pub indicator: String,
    /// Type of indicator
    #[serde(rename = "indicatorType")]
    pub indicator_type: IndicatorType,
    /// Investigation depth level
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<Depth>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::InvestigateContext>>,
}

impl InvestigateRequest {
    /// Request for comprehensive AI threat investigation
    pub fn new(indicator: String, indicator_type: IndicatorType) -> InvestigateRequest {
        InvestigateRequest {
            indicator,
            indicator_type,
            depth: None,
            context: None,
        }
    }
}
/// Type of indicator
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IndicatorType {
    #[serde(rename = "ip")]
    Ip,
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "hash")]
    Hash,
}

impl Default for IndicatorType {
    fn default() -> IndicatorType {
        Self::Ip
    }
}
/// Investigation depth level
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Depth {
    #[serde(rename = "quick")]
    Quick,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "comprehensive")]
    Comprehensive,
}

impl Default for Depth {
    fn default() -> Depth {
        Self::Quick
    }
}

