/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobResponse : Response returned when an asynchronous job is created. Contains the job ID and status URL for polling.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobResponse {
    /// Unique identifier for the job. Use this ID to poll for job status and results.
    #[serde(rename = "jobId")]
    pub job_id: String,
    /// Current status of the job
    #[serde(rename = "status")]
    pub status: Status,
    /// URL endpoint to poll for job status and results. Typically `/v1/ops/jobs/{jobId}`.
    #[serde(rename = "statusUrl")]
    pub status_url: String,
    /// Human-readable message describing the job acceptance or current state
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl JobResponse {
    /// Response returned when an asynchronous job is created. Contains the job ID and status URL for polling.
    pub fn new(job_id: String, status: Status, status_url: String) -> JobResponse {
        JobResponse {
            job_id,
            status,
            status_url,
            message: None,
        }
    }
}
/// Current status of the job
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

