/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinksInfo : Link statistics and top sources/destinations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinksInfo {
    /// Total number of links
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Top linking sources (for incoming links)
    #[serde(rename = "top_sources", skip_serializing_if = "Option::is_none")]
    pub top_sources: Option<Vec<String>>,
    /// Top link destinations (for outgoing links)
    #[serde(rename = "top_destinations", skip_serializing_if = "Option::is_none")]
    pub top_destinations: Option<Vec<String>>,
}

impl LinksInfo {
    /// Link statistics and top sources/destinations
    pub fn new() -> LinksInfo {
        LinksInfo {
            total: None,
            top_sources: None,
            top_destinations: None,
        }
    }
}

