/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetadataInfo : Response metadata including data sources and any errors encountered
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataInfo {
    /// List of data sources used to build this response
    #[serde(rename = "data_sources", skip_serializing_if = "Option::is_none")]
    pub data_sources: Option<Vec<String>>,
    /// Any non-fatal errors encountered during data collection. Empty if all sources succeeded.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
}

impl MetadataInfo {
    /// Response metadata including data sources and any errors encountered
    pub fn new() -> MetadataInfo {
        MetadataInfo {
            data_sources: None,
            errors: None,
        }
    }
}

