/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelInfo : ML model information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Model version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Last updated timestamp
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl ModelInfo {
    /// ML model information
    pub fn new() -> ModelInfo {
        ModelInfo {
            version: None,
            last_updated: None,
        }
    }
}

