/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitoringAlertRequest : Configuration for creating monitoring alert rules with notification channels
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitoringAlertRequest {
    /// Type of alert condition to monitor
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Threshold in days (for ssl_expiring alerts). Alert triggers when SSL cert expires within this many days.
    #[serde(rename = "threshold_days", skip_serializing_if = "Option::is_none")]
    pub threshold_days: Option<i32>,
    /// Notification channels to use for alerts
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<String>>,
    /// Email address for alert notifications
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Slack webhook URL for notifications
    #[serde(rename = "slack_webhook", skip_serializing_if = "Option::is_none")]
    pub slack_webhook: Option<String>,
    /// Custom webhook URL for notifications (will receive POST with alert data)
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
    /// PagerDuty integration key for incident creation
    #[serde(rename = "pagerduty_key", skip_serializing_if = "Option::is_none")]
    pub pagerduty_key: Option<String>,
}

impl MonitoringAlertRequest {
    /// Configuration for creating monitoring alert rules with notification channels
    pub fn new(r#type: Type) -> MonitoringAlertRequest {
        MonitoringAlertRequest {
            r#type,
            threshold_days: None,
            channels: None,
            email: None,
            slack_webhook: None,
            webhook_url: None,
            pagerduty_key: None,
        }
    }
}
/// Type of alert condition to monitor
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "downtime")]
    Downtime,
    #[serde(rename = "dns_change")]
    DnsChange,
    #[serde(rename = "whois_change")]
    WhoisChange,
    #[serde(rename = "ssl_expiring")]
    SslExpiring,
    #[serde(rename = "content_change")]
    ContentChange,
    #[serde(rename = "technology_change")]
    TechnologyChange,
}

impl Default for Type {
    fn default() -> Type {
        Self::Downtime
    }
}

