/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitorAssertions : Assertions to validate check results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorAssertions {
    /// Expected response headers
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    /// Expected HTTP status code
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    /// Maximum response time in milliseconds
    #[serde(rename = "maxResponseTime", skip_serializing_if = "Option::is_none")]
    pub max_response_time: Option<i64>,
    /// Text that must be present in response body
    #[serde(rename = "containsText", skip_serializing_if = "Option::is_none")]
    pub contains_text: Option<String>,
    /// Text that must NOT be present in response body
    #[serde(rename = "notContainsText", skip_serializing_if = "Option::is_none")]
    pub not_contains_text: Option<String>,
    /// Minimum SSL certificate days until expiry (for ssl checks)
    #[serde(rename = "sslDaysUntilExpiry", skip_serializing_if = "Option::is_none")]
    pub ssl_days_until_expiry: Option<i32>,
    /// Expected DNS record value (for dns checks)
    #[serde(rename = "dnsRecordValue", skip_serializing_if = "Option::is_none")]
    pub dns_record_value: Option<String>,
    /// DNS record type (for dns checks)
    #[serde(rename = "dnsRecordType", skip_serializing_if = "Option::is_none")]
    pub dns_record_type: Option<DnsRecordType>,
}

impl MonitorAssertions {
    /// Assertions to validate check results
    pub fn new() -> MonitorAssertions {
        MonitorAssertions {
            headers: None,
            status_code: None,
            max_response_time: None,
            contains_text: None,
            not_contains_text: None,
            ssl_days_until_expiry: None,
            dns_record_value: None,
            dns_record_type: None,
        }
    }
}
/// DNS record type (for dns checks)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DnsRecordType {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "AAAA")]
    Aaaa,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "NS")]
    Ns,
}

impl Default for DnsRecordType {
    fn default() -> DnsRecordType {
        Self::A
    }
}

