/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitorDashboardResponse : Monitoring dashboard summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorDashboardResponse {
    /// Total number of checks
    #[serde(rename = "totalChecks", skip_serializing_if = "Option::is_none")]
    pub total_checks: Option<i32>,
    /// Number of passing checks
    #[serde(rename = "passingChecks", skip_serializing_if = "Option::is_none")]
    pub passing_checks: Option<i32>,
    /// Number of failing checks
    #[serde(rename = "failingChecks", skip_serializing_if = "Option::is_none")]
    pub failing_checks: Option<i32>,
    /// Number of degraded checks
    #[serde(rename = "degradedChecks", skip_serializing_if = "Option::is_none")]
    pub degraded_checks: Option<i32>,
    /// Overall status
    #[serde(rename = "overallStatus", skip_serializing_if = "Option::is_none")]
    pub overall_status: Option<OverallStatus>,
    /// Average uptime percentage over the last 24 hours
    #[serde(rename = "avgUptime24Hours", skip_serializing_if = "Option::is_none")]
    pub avg_uptime24_hours: Option<f64>,
    /// Average uptime percentage over the last 7 days
    #[serde(rename = "avgUptime7Days", skip_serializing_if = "Option::is_none")]
    pub avg_uptime7_days: Option<f64>,
    /// Average uptime percentage over the last 30 days
    #[serde(rename = "avgUptime30Days", skip_serializing_if = "Option::is_none")]
    pub avg_uptime30_days: Option<f64>,
    /// Average response time across all checks in milliseconds
    #[serde(rename = "avgResponseTime", skip_serializing_if = "Option::is_none")]
    pub avg_response_time: Option<i64>,
    /// Count of checks by type
    #[serde(rename = "checksByType", skip_serializing_if = "Option::is_none")]
    pub checks_by_type: Option<std::collections::HashMap<String, i32>>,
    /// Count of checks by status
    #[serde(rename = "checksByStatus", skip_serializing_if = "Option::is_none")]
    pub checks_by_status: Option<std::collections::HashMap<String, i32>>,
    /// When this dashboard data was last updated
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl MonitorDashboardResponse {
    /// Monitoring dashboard summary
    pub fn new() -> MonitorDashboardResponse {
        MonitorDashboardResponse {
            total_checks: None,
            passing_checks: None,
            failing_checks: None,
            degraded_checks: None,
            overall_status: None,
            avg_uptime24_hours: None,
            avg_uptime7_days: None,
            avg_uptime30_days: None,
            avg_response_time: None,
            checks_by_type: None,
            checks_by_status: None,
            last_updated: None,
        }
    }
}
/// Overall status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OverallStatus {
    #[serde(rename = "passing")]
    Passing,
    #[serde(rename = "failing")]
    Failing,
    #[serde(rename = "degraded")]
    Degraded,
}

impl Default for OverallStatus {
    fn default() -> OverallStatus {
        Self::Passing
    }
}

