/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitorCheckResponse : Monitoring check details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorCheckResponse {
    /// Unique identifier for the check
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the monitoring check
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// URL being monitored
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Type of check
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// Current status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Whether the check is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Check frequency in minutes
    #[serde(rename = "frequency", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<i32>,
    /// Locations where check runs
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<String>>,
    /// Whether the check is muted (no alerts)
    #[serde(rename = "muted", skip_serializing_if = "Option::is_none")]
    pub muted: Option<bool>,
    /// HTTP method used for API checks
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(rename = "assertions", skip_serializing_if = "Option::is_none")]
    pub assertions: Option<Box<models::MonitorAssertions>>,
    /// Last time the check ran
    #[serde(rename = "lastRunAt", skip_serializing_if = "Option::is_none")]
    pub last_run_at: Option<String>,
    /// When the check was created
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the check was last updated
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Uptime percentage over the last 24 hours
    #[serde(rename = "uptime24Hours", skip_serializing_if = "Option::is_none")]
    pub uptime24_hours: Option<f64>,
    /// Uptime percentage over the last 7 days
    #[serde(rename = "uptime7Days", skip_serializing_if = "Option::is_none")]
    pub uptime7_days: Option<f64>,
    /// Uptime percentage over the last 30 days
    #[serde(rename = "uptime30Days", skip_serializing_if = "Option::is_none")]
    pub uptime30_days: Option<f64>,
    /// Average response time in milliseconds
    #[serde(rename = "responseTime", skip_serializing_if = "Option::is_none")]
    pub response_time: Option<i64>,
}

impl MonitorCheckResponse {
    /// Monitoring check details
    pub fn new() -> MonitorCheckResponse {
        MonitorCheckResponse {
            id: None,
            name: None,
            url: None,
            r#type: None,
            status: None,
            enabled: None,
            frequency: None,
            locations: None,
            muted: None,
            method: None,
            assertions: None,
            last_run_at: None,
            created_at: None,
            updated_at: None,
            uptime24_hours: None,
            uptime7_days: None,
            uptime30_days: None,
            response_time: None,
        }
    }
}
/// Type of check
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "ssl")]
    Ssl,
    #[serde(rename = "dns")]
    Dns,
}

impl Default for Type {
    fn default() -> Type {
        Self::Api
    }
}
/// Current status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "passing")]
    Passing,
    #[serde(rename = "failing")]
    Failing,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Passing
    }
}

