/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatternMatching : Pattern matching insights
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatternMatching {
    /// Pattern confidence score
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    /// Matched pattern types
    #[serde(rename = "matchedPatterns", skip_serializing_if = "Option::is_none")]
    pub matched_patterns: Option<Vec<String>>,
}

impl PatternMatching {
    /// Pattern matching insights
    pub fn new() -> PatternMatching {
        PatternMatching {
            confidence: None,
            matched_patterns: None,
        }
    }
}

