/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PercentileInfo : Percentile distribution
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PercentileInfo {
    /// 25th percentile risk score
    #[serde(rename = "p25", skip_serializing_if = "Option::is_none")]
    pub p25: Option<f64>,
    /// 50th percentile risk score (median)
    #[serde(rename = "p50", skip_serializing_if = "Option::is_none")]
    pub p50: Option<f64>,
    /// 75th percentile risk score
    #[serde(rename = "p75", skip_serializing_if = "Option::is_none")]
    pub p75: Option<f64>,
    /// 90th percentile risk score
    #[serde(rename = "p90", skip_serializing_if = "Option::is_none")]
    pub p90: Option<f64>,
}

impl PercentileInfo {
    /// Percentile distribution
    pub fn new() -> PercentileInfo {
        PercentileInfo {
            p25: None,
            p50: None,
            p75: None,
            p90: None,
        }
    }
}

