/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PredictiveRiskResponse : ML-based predictive risk assessment for an indicator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PredictiveRiskResponse {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::QueryInfo>>,
    #[serde(rename = "currentAssessment", skip_serializing_if = "Option::is_none")]
    pub current_assessment: Option<Box<models::CurrentAssessment>>,
    #[serde(rename = "predictions", skip_serializing_if = "Option::is_none")]
    pub predictions: Option<Box<models::Predictions>>,
    #[serde(rename = "trajectory", skip_serializing_if = "Option::is_none")]
    pub trajectory: Option<Box<models::TrajectoryInfo>>,
    /// Contributing risk factors
    #[serde(rename = "riskFactors", skip_serializing_if = "Option::is_none")]
    pub risk_factors: Option<Vec<models::RiskFactor>>,
    #[serde(rename = "patternMatching", skip_serializing_if = "Option::is_none")]
    pub pattern_matching: Option<Box<models::PatternMatching>>,
    /// Early warning signals
    #[serde(rename = "earlyWarnings", skip_serializing_if = "Option::is_none")]
    pub early_warnings: Option<Vec<models::EarlyWarning>>,
    /// Similar historical cases
    #[serde(rename = "similarCases", skip_serializing_if = "Option::is_none")]
    pub similar_cases: Option<Vec<models::SimilarCase>>,
    #[serde(rename = "modelInfo", skip_serializing_if = "Option::is_none")]
    pub model_info: Option<Box<models::ModelInfo>>,
}

impl PredictiveRiskResponse {
    /// ML-based predictive risk assessment for an indicator
    pub fn new() -> PredictiveRiskResponse {
        PredictiveRiskResponse {
            query: None,
            current_assessment: None,
            predictions: None,
            trajectory: None,
            risk_factors: None,
            pattern_matching: None,
            early_warnings: None,
            similar_cases: None,
            model_info: None,
        }
    }
}

