/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryInfo {
    #[serde(rename = "indicator", skip_serializing_if = "Option::is_none")]
    pub indicator: Option<String>,
    #[serde(rename = "indicator_type", skip_serializing_if = "Option::is_none")]
    pub indicator_type: Option<String>,
    #[serde(rename = "history_type", skip_serializing_if = "Option::is_none")]
    pub history_type: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "response_time_ms", skip_serializing_if = "Option::is_none")]
    pub response_time_ms: Option<i64>,
}

impl QueryInfo {
    pub fn new() -> QueryInfo {
        QueryInfo {
            indicator: None,
            indicator_type: None,
            history_type: None,
            timestamp: None,
            response_time_ms: None,
        }
    }
}

