/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReputationInfo : Reputation scoring and blacklist information for threat assessment
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReputationInfo {
    /// Composite risk score (0-10, higher = riskier)
    #[serde(rename = "risk_score", skip_serializing_if = "Option::is_none")]
    pub risk_score: Option<f64>,
    #[serde(rename = "blacklists", skip_serializing_if = "Option::is_none")]
    pub blacklists: Option<Box<models::BlacklistScores>>,
    #[serde(rename = "domain_reputation", skip_serializing_if = "Option::is_none")]
    pub domain_reputation: Option<Box<models::DomainReputationScores>>,
}

impl ReputationInfo {
    /// Reputation scoring and blacklist information for threat assessment
    pub fn new() -> ReputationInfo {
        ReputationInfo {
            risk_score: None,
            blacklists: None,
            domain_reputation: None,
        }
    }
}

