/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskFactor : Individual risk factor
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskFactor {
    /// Factor name
    #[serde(rename = "factor", skip_serializing_if = "Option::is_none")]
    pub factor: Option<String>,
    /// Factor weight (0-1)
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    /// Contribution to score
    #[serde(rename = "contribution", skip_serializing_if = "Option::is_none")]
    pub contribution: Option<f64>,
    /// Factor description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl RiskFactor {
    /// Individual risk factor
    pub fn new() -> RiskFactor {
        RiskFactor {
            factor: None,
            weight: None,
            contribution: None,
            description: None,
        }
    }
}

