/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScanRequest : Request for initiating a domain infrastructure scan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanRequest {
    /// The target domain to scan
    #[serde(rename = "domain")]
    pub domain: String,
    /// Type of scan to perform. Determines the depth and modules used in the scan.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl ScanRequest {
    /// Request for initiating a domain infrastructure scan
    pub fn new(domain: String) -> ScanRequest {
        ScanRequest {
            domain,
            r#type: None,
        }
    }
}
/// Type of scan to perform. Determines the depth and modules used in the scan.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "comprehensive")]
    Comprehensive,
    #[serde(rename = "subdomains")]
    Subdomains,
    #[serde(rename = "ports")]
    Ports,
    #[serde(rename = "technologies")]
    Technologies,
    #[serde(rename = "vulnerabilities")]
    Vulnerabilities,
    #[serde(rename = "ssl")]
    Ssl,
    #[serde(rename = "dns")]
    Dns,
    #[serde(rename = "whois")]
    Whois,
}

impl Default for Type {
    fn default() -> Type {
        Self::Comprehensive
    }
}

