/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScreenshotOptions : Configuration options for screenshot capture
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotOptions {
    /// Viewport width in pixels
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    /// Viewport height in pixels
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// Capture the full page height (scrolling screenshot)
    #[serde(rename = "full_page", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    /// Wait time in milliseconds before taking screenshot
    #[serde(rename = "wait_time", skip_serializing_if = "Option::is_none")]
    pub wait_time: Option<i32>,
    /// Image format for the screenshot
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// Image quality (1-100, only for jpeg/webp)
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    /// User agent string to use for the request
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    /// Enable JavaScript execution
    #[serde(rename = "javascript", skip_serializing_if = "Option::is_none")]
    pub javascript: Option<bool>,
    /// Block ads and trackers
    #[serde(rename = "block_ads", skip_serializing_if = "Option::is_none")]
    pub block_ads: Option<bool>,
    /// Accept cookies consent if prompted
    #[serde(rename = "accept_cookies", skip_serializing_if = "Option::is_none")]
    pub accept_cookies: Option<bool>,
}

impl ScreenshotOptions {
    /// Configuration options for screenshot capture
    pub fn new() -> ScreenshotOptions {
        ScreenshotOptions {
            width: None,
            height: None,
            full_page: None,
            wait_time: None,
            format: None,
            quality: None,
            user_agent: None,
            javascript: None,
            block_ads: None,
            accept_cookies: None,
        }
    }
}
/// Image format for the screenshot
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "png")]
    Png,
    #[serde(rename = "jpeg")]
    Jpeg,
    #[serde(rename = "webp")]
    Webp,
}

impl Default for Format {
    fn default() -> Format {
        Self::Png
    }
}

