/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchRequest : Search query for finding indicators matching specific criteria. Powerful for threat hunting and infrastructure discovery.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequest {
    /// Search query using field:value syntax. Supports multiple fields combined with logical operators.  **Supported Fields:** - WHOIS: `registrantCompany`, `registrantName`, `registrantEmail`, `registrar` - Network: `asn`, `network`, `country_code`, `city` - Domain: `tld`, `domain_length`, `creation_date`  **Examples:** - `registrantCompany:EvilCorp` - Find domains by registrant - `asn:15169 AND country_code:US` - Complex query with AND - `registrantEmail:admin@example.com` - Find domains by email 
    #[serde(rename = "query")]
    pub query: String,
    /// Specific field to search in. If provided, the query is interpreted as a value for this field.
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    /// Additional filters to narrow down search results. Applied after query matching.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<std::collections::HashMap<String, String>>,
    /// Maximum number of results to return per page
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Number of results to skip for pagination. Use with limit for paginated results.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Field to sort results by
    #[serde(rename = "sort_by", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<SortBy>,
    /// Sort order
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<SortOrder>,
}

impl SearchRequest {
    /// Search query for finding indicators matching specific criteria. Powerful for threat hunting and infrastructure discovery.
    pub fn new(query: String) -> SearchRequest {
        SearchRequest {
            query,
            field: None,
            filters: None,
            limit: None,
            offset: None,
            sort_by: None,
            sort_order: None,
        }
    }
}
/// Field to sort results by
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortBy {
    #[serde(rename = "registration_date")]
    RegistrationDate,
    #[serde(rename = "expiration_date")]
    ExpirationDate,
    #[serde(rename = "risk_score")]
    RiskScore,
    #[serde(rename = "domain_name")]
    DomainName,
    #[serde(rename = "asn")]
    Asn,
}

impl Default for SortBy {
    fn default() -> SortBy {
        Self::RegistrationDate
    }
}
/// Sort order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

impl Default for SortOrder {
    fn default() -> SortOrder {
        Self::Asc
    }
}

