/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimilarCase : Similar historical case
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimilarCase {
    /// Similarity score (0-1)
    #[serde(rename = "similarity", skip_serializing_if = "Option::is_none")]
    pub similarity: Option<f64>,
    /// Case outcome
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
    /// Case ID
    #[serde(rename = "caseId", skip_serializing_if = "Option::is_none")]
    pub case_id: Option<String>,
}

impl SimilarCase {
    /// Similar historical case
    pub fn new() -> SimilarCase {
        SimilarCase {
            similarity: None,
            outcome: None,
            case_id: None,
        }
    }
}

