/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubdomainInfo : Detailed information about a discovered subdomain
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubdomainInfo {
    /// The full subdomain name
    #[serde(rename = "subdomain")]
    pub subdomain: String,
    /// IP addresses associated with the subdomain
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<String>>,
    /// First time this subdomain was observed
    #[serde(rename = "first_seen", skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,
    /// Last time this subdomain was observed
    #[serde(rename = "last_seen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
    /// Type of subdomain record
    #[serde(rename = "record_type", skip_serializing_if = "Option::is_none")]
    pub record_type: Option<RecordType>,
    /// Current status of the subdomain
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Technology stack detected on this subdomain
    #[serde(rename = "technologies", skip_serializing_if = "Option::is_none")]
    pub technologies: Option<Vec<String>>,
    /// Risk score for this subdomain (0-100)
    #[serde(rename = "risk_score", skip_serializing_if = "Option::is_none")]
    pub risk_score: Option<i32>,
}

impl SubdomainInfo {
    /// Detailed information about a discovered subdomain
    pub fn new(subdomain: String) -> SubdomainInfo {
        SubdomainInfo {
            subdomain,
            ip_addresses: None,
            first_seen: None,
            last_seen: None,
            record_type: None,
            status: None,
            technologies: None,
            risk_score: None,
        }
    }
}
/// Type of subdomain record
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecordType {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "AAAA")]
    Aaaa,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "NS")]
    Ns,
}

impl Default for RecordType {
    fn default() -> RecordType {
        Self::A
    }
}
/// Current status of the subdomain
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "parked")]
    Parked,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

