/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SummaryInfo : Executive summary with the most important facts for quick decision-making
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryInfo {
    /// Primary organization name
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// Primary location
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Network range or CIDR
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    /// Domain registrar
    #[serde(rename = "registrar", skip_serializing_if = "Option::is_none")]
    pub registrar: Option<String>,
    /// Domain status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Primary ASN
    #[serde(rename = "asn_primary", skip_serializing_if = "Option::is_none")]
    pub asn_primary: Option<String>,
    /// Composite risk score (0-10, higher is riskier)
    #[serde(rename = "risk_score", skip_serializing_if = "Option::is_none")]
    pub risk_score: Option<f64>,
    /// IP classification
    #[serde(rename = "ip_type", skip_serializing_if = "Option::is_none")]
    pub ip_type: Option<IpType>,
    /// Total number of domains resolving to this IP
    #[serde(rename = "total_domains", skip_serializing_if = "Option::is_none")]
    pub total_domains: Option<i32>,
    /// The domain name
    #[serde(rename = "domain_name", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// Domain registration date
    #[serde(rename = "registration_date", skip_serializing_if = "Option::is_none")]
    pub registration_date: Option<String>,
    /// Domain expiration date
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    /// Primary DNS provider
    #[serde(rename = "dns_provider", skip_serializing_if = "Option::is_none")]
    pub dns_provider: Option<String>,
    /// Number of incoming links/backlinks
    #[serde(rename = "total_links_in", skip_serializing_if = "Option::is_none")]
    pub total_links_in: Option<i32>,
    /// Number of outgoing links
    #[serde(rename = "total_links_out", skip_serializing_if = "Option::is_none")]
    pub total_links_out: Option<i32>,
}

impl SummaryInfo {
    /// Executive summary with the most important facts for quick decision-making
    pub fn new() -> SummaryInfo {
        SummaryInfo {
            organization: None,
            location: None,
            network: None,
            registrar: None,
            status: None,
            asn_primary: None,
            risk_score: None,
            ip_type: None,
            total_domains: None,
            domain_name: None,
            registration_date: None,
            expiration_date: None,
            dns_provider: None,
            total_links_in: None,
            total_links_out: None,
        }
    }
}
/// Domain status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// IP classification
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IpType {
    #[serde(rename = "residential")]
    Residential,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "datacenter")]
    Datacenter,
    #[serde(rename = "hosting")]
    Hosting,
    #[serde(rename = "vpn")]
    Vpn,
    #[serde(rename = "proxy")]
    Proxy,
    #[serde(rename = "tor")]
    Tor,
    #[serde(rename = "mobile")]
    Mobile,
}

impl Default for IpType {
    fn default() -> IpType {
        Self::Residential
    }
}

