/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TechniqueConfig : Detailed configuration for each domain variation technique
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TechniqueConfig {
    #[serde(rename = "typosquatting", skip_serializing_if = "Option::is_none")]
    pub typosquatting: Option<Box<models::TyposquattingConfig>>,
    #[serde(rename = "homoglyph", skip_serializing_if = "Option::is_none")]
    pub homoglyph: Option<Box<models::HomoglyphConfig>>,
    #[serde(rename = "bitsquatting", skip_serializing_if = "Option::is_none")]
    pub bitsquatting: Option<Box<models::BitsquattingConfig>>,
    #[serde(rename = "tld_variation", skip_serializing_if = "Option::is_none")]
    pub tld_variation: Option<Box<models::TldVariationConfig>>,
}

impl TechniqueConfig {
    /// Detailed configuration for each domain variation technique
    pub fn new() -> TechniqueConfig {
        TechniqueConfig {
            typosquatting: None,
            homoglyph: None,
            bitsquatting: None,
            tld_variation: None,
        }
    }
}

