/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TldVariationConfig : Configuration for top-level domain variations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TldVariationConfig {
    /// Include common TLD variations (.com, .net, .org, etc.)
    #[serde(rename = "common_tlds", skip_serializing_if = "Option::is_none")]
    pub common_tlds: Option<bool>,
    /// Include country-code TLDs
    #[serde(rename = "country_tlds", skip_serializing_if = "Option::is_none")]
    pub country_tlds: Option<bool>,
    /// Include new generic TLDs (.app, .dev, .cloud, etc.)
    #[serde(rename = "new_gtlds", skip_serializing_if = "Option::is_none")]
    pub new_gtlds: Option<bool>,
    /// Custom TLDs to check
    #[serde(rename = "custom_tlds", skip_serializing_if = "Option::is_none")]
    pub custom_tlds: Option<Vec<String>>,
}

impl TldVariationConfig {
    /// Configuration for top-level domain variations
    pub fn new() -> TldVariationConfig {
        TldVariationConfig {
            common_tlds: None,
            country_tlds: None,
            new_gtlds: None,
            custom_tlds: None,
        }
    }
}

