/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrackingConfig : Change tracking configuration for an indicator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackingConfig {
    /// Whether tracking is currently enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Fields being tracked for changes
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    /// Check frequency: hourly, daily, or weekly
    #[serde(rename = "frequency", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    /// When tracking was first started
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the last check was performed
    #[serde(rename = "lastCheck", skip_serializing_if = "Option::is_none")]
    pub last_check: Option<String>,
    /// When the next check is scheduled
    #[serde(rename = "nextCheck", skip_serializing_if = "Option::is_none")]
    pub next_check: Option<String>,
    /// Username of the owner
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Indicator type: ip or domain
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Indicator value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl TrackingConfig {
    /// Change tracking configuration for an indicator
    pub fn new() -> TrackingConfig {
        TrackingConfig {
            enabled: None,
            fields: None,
            frequency: None,
            created_at: None,
            last_check: None,
            next_check: None,
            username: None,
            r#type: None,
            value: None,
        }
    }
}

