/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrendData : Historical trend data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrendData {
    /// Trend direction
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    /// 30-day risk trend
    #[serde(rename = "riskTrend30d", skip_serializing_if = "Option::is_none")]
    pub risk_trend30d: Option<String>,
    /// Risk score change percentage
    #[serde(rename = "changePercent", skip_serializing_if = "Option::is_none")]
    pub change_percent: Option<f64>,
}

impl TrendData {
    /// Historical trend data
    pub fn new() -> TrendData {
        TrendData {
            direction: None,
            risk_trend30d: None,
            change_percent: None,
        }
    }
}

