/*
 * Whisper Security API
 *
 * Enterprise threat intelligence and security operations API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TyposquattingConfig : Configuration for typosquatting variations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TyposquattingConfig {
    /// Include character omission variations
    #[serde(rename = "character_omission", skip_serializing_if = "Option::is_none")]
    pub character_omission: Option<bool>,
    /// Include character swap variations
    #[serde(rename = "character_swap", skip_serializing_if = "Option::is_none")]
    pub character_swap: Option<bool>,
    /// Include double character variations
    #[serde(rename = "double_character", skip_serializing_if = "Option::is_none")]
    pub double_character: Option<bool>,
    /// Include keyboard proximity variations
    #[serde(rename = "keyboard_proximity", skip_serializing_if = "Option::is_none")]
    pub keyboard_proximity: Option<bool>,
}

impl TyposquattingConfig {
    /// Configuration for typosquatting variations
    pub fn new() -> TyposquattingConfig {
        TyposquattingConfig {
            character_omission: None,
            character_swap: None,
            double_character: None,
            keyboard_proximity: None,
        }
    }
}

